slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: localization
    map_file_name: /home/siva/a_ws/src/turtlebot3/maps/mapofmaze
    # map_start_pose: [-4.0, 4.0, 0.0]
    map_start_at_dock: true

    # Slam Toolbox Parameters
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 10.0 # Matches your Xacro LiDAR max
    minimum_time_interval: 0.06
    transform_timeout: 0.1
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000 
    enable_interactive_mode: true

    # Scan Matcher Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 15
    scan_buffer_maximum_scan_distance: 15.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 2.0
    loop_search_maximum_distance: 5.0
    do_loop_closing: false

    # Loop closure parameters
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.1
    loop_match_minimum_response_fine: 0.1
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1