controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    # Wheel joints
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    # Kinematics
    wheel_separation: 0.160
    wheel_radius: 0.033

    # Odometry
    odom_frame_id: odom
    base_frame_id: base_footprint
    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true

    # Command parameters
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.22
    linear.x.min_velocity: -0.22
    linear.x.max_acceleration: 1.0
    
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 2.84
    angular.z.max_acceleration: 3.2